version: "3.8"

services:
  backend:
    build:
      context: "./"
      dockerfile: Dockerfile
      target: development
    image: city-search-backend:dev
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
